# Game Constants
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 710
NUM_LETTERS = 5
MAX_GUESSES = 6
FPS = 60

# Guess Board
CELL_PADDING = 5
CELL_SIZE = 60
TEXT_PADDING_Y = 3
BOARD_START_X = 47.5
BOARD_START_Y = 100
BOARD_WIDTH = NUM_LETTERS * CELL_SIZE + (NUM_LETTERS - 1) * CELL_PADDING
BOARD_HEIGHT = MAX_GUESSES * CELL_SIZE + (MAX_GUESSES - 1) * CELL_PADDING

# On Screen Keyboard
KEYBUTTON_WIDTH = 40
KEYBUTTON_HEIGHT = 50
KEYBUTTON_TEXTPADDING = 1
KEYBUTTON_PADDING = 5
KEYBOARD_ROWS = [
    ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
    ["a", "s", "d", "f", "g", "h", "j", "k", "l"],
    ["z", "x", "c", "v", "b", "n", "m"],
]
KEYBOARD_NUM_ROWS = len(KEYBOARD_ROWS)
KEYBOARD_NUM_KEYS = len(KEYBOARD_ROWS[0])
KEYROW_OFFSETS = [0, 20, 65]
KEYBOARD_WIDTH = (
    KEYBOARD_NUM_KEYS * KEYBUTTON_WIDTH + (KEYBOARD_NUM_KEYS - 1) * KEYBUTTON_PADDING
)
KEYBOARD_HEIGHT = (
    KEYBOARD_NUM_ROWS * KEYBUTTON_HEIGHT + (KEYBOARD_NUM_ROWS - 1) * KEYBUTTON_PADDING
)

# Reset Button
RESET_BUTTON_WIDTH = 100
RESET_BUTTON_HEIGHT = 40
RESET_BUTTON_PADDING = 10

# Popup
POPUP_WIDTH = 200
POPUP_HEIGHT = 150
MESSAGE_WIDTH = 200
MESSAGE_HEIGHT = 75
BUTTON_WIDTH = 75
BUTTON_HEIGHT = 30

# Colors
BLACK = (18, 18, 18)
LIGHT_GREY = (58, 58, 60)
DARK_GREY = (30, 30, 32)
WHITE = (255, 255, 255)
YELLOW = (185, 158, 25)
GREEN = (61, 143, 69)
